Bring RKE2 docs up to date with new CIS 1.23
rancher/rke2-docs pull request #10
Opened 2022-11-08 20:17 UTC by dereknola

Copy over work from https://github.com/rancher/rke2/pull/3360 into the new docs site, with minor changes to match the "docusaurus" style guides.

Signed-off-by: Derek Nola <derek.nola@suse.com>

2022-11-10 18:05 UTC, VestigeJ commented on docs/security/hardening_guide.md
> +When RKE2 is installed, it creates a sysctl config file to set the required parameters appropriately. However, it does not automatically configures the host to use this configuration. You must do thi
Remove s on configures

"it does not automatically configure" vs configures

2022-11-10 18:37 UTC, VestigeJ commented on docs/security/cis_self_assessment123.md
> +If you need to run containers which require hostIPC, this should be definited in a separate policy and you should carefully check to ensure that only limited service accounts and users are given perm
** " this should be defined " not definited

2022-11-10 18:45 UTC, VestigeJ requested changes
Just the two spelling changes and then it looks good to me

2022-11-10 22:23 UTC, dereknola commented on docs/security/cis_self_assessment123.md
> +If you need to run containers which require hostIPC, this should be definited in a separate policy and you should carefully check to ensure that only limited service accounts and users are given perm
LOL, this language is pulled directly from the CIS offical benchmark https://paper.bobylive.com/Security/CIS/CIS-Kubernetes-Benchmark-V1_23--PDF.pdf see section 5.2.4. 

I will fix their misspelling :)

2022-11-18 17:03 UTC, briandowns approved these changes

2022-11-18 17:30 UTC, merged