Add `rke2-agent` restart step to Certificate Rotation
rancher/rke2-docs pull request #107
Opened 2023-09-27 05:58 UTC by masap

If a worker node was created by `rke2-agent`, we need to restart it as well to rotate it's own certificates. I confirmed certificates at `/var/lib/rancher/rke2/agent/` were rotated by restart `rke2-agent`.

2023-09-27 16:52 UTC, brandond requested changes

2023-09-27 16:52 UTC, brandond commented on docs/advanced.md
> +After certificate rotation of server, restart rke2-agent as well to rotate kubelet certificates in worker nodes.
I'm not sure this actually belongs here. Agent certificates are renewed every time the agent starts, so this command can actually be done at any time, independent from server certificate rotation.

We should also make it clear that this service should be restarted on agent nodes only, to avoid having users try to restart the agent service on servers.

2023-09-28 05:44 UTC, masap commented on docs/advanced.md
> +After certificate rotation of server, restart rke2-agent as well to rotate kubelet certificates in worker nodes.
@brandond Thank you for comment.

> I'm not sure this actually belongs here. Agent certificates are renewed every time the agent starts, so this command can actually be done at any time, independent from server certificate rotation.

Right, only restarting `rke2-agent` is needed. I fixed document.

> We should also make it clear that this service should be restarted on agent nodes only, to avoid having users try to restart the agent service on servers.

I also added the statement to run on agent node and confirmed restarting `rke2-agent` renewed certificates at `/var/lib/rancher/rke2/agent/`.

2023-10-02 17:41 UTC, dereknola approved these changes

2023-10-02 18:43 UTC, brandond approved these changes

2023-10-03 18:10 UTC, merged