Adapt network_options to docusarous
rancher/rke2-docs pull request #11
Opened 2022-11-14 15:13 UTC by manuelbuil

Adapts the current network_options file to docusarous

Now we have tabs and small windows highlighting notes and warnings!

![image](https://user-images.githubusercontent.com/16151814/201868763-a7bb0642-dc7d-41e7-b0d8-466ce3e411fe.png)

Signed-off-by: Manuel Buil <mbuil@suse.com>

2022-11-14 17:31 UTC, dereknola requested changes
Just under the title add, otherwise tabs wont render
```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
```

2022-11-14 17:31 UTC, dereknola commented on docs/install/network_options.md
>      Calico automatically detects the RKE2 configuration for dual-stack and does not need any extra configuration. When deployed in dual-stack mode, it creates two different ippool resources. Note tha
```suggestion
Calico automatically detects the RKE2 configuration for dual-stack and does not need any extra configuration. When deployed in dual-stack mode, it creates two different ippool resources. Note that when using dual-stack, calico leverages BGP instead of VXLAN encapsulation. Dual-stack and BGP are currently not supported in the windows installations of RKE2.
```

2022-11-14 17:31 UTC, dereknola commented on docs/install/network_options.md
>      Cilium automatically detects the RKE2 configuration for dual-stack and does not need any extra configuration.
```suggestion
Cilium automatically detects the RKE2 configuration for dual-stack and does not need any extra configuration.
```

Remove tab, otherwise sentence will be placed in a code block 
![image](https://user-images.githubusercontent.com/11727736/201726536-21ff182f-da91-4193-8271-5351732cb515.png)

2022-11-14 17:31 UTC, dereknola commented on docs/install/network_options.md
>      Canal automatically detects the RKE2 configuration for dual-stack and does not need any extra configuration. Dual-stack is currently not supported in the windows installations of RKE2.
```suggestion
Canal automatically detects the RKE2 configuration for dual-stack and does not need any extra configuration. Dual-stack is currently not supported in the windows installations of RKE2.
```

2022-11-15 08:28 UTC, manuelbuil commented
> import Tabs from '@theme/Tabs';
> import TabItem from '@theme/TabItem';



> Just under the title add, otherwise tabs wont render
> 
> ```
> import Tabs from '@theme/Tabs';
> import TabItem from '@theme/TabItem';
> ```

Thanks!

2022-11-21 17:08 UTC, dereknola approved these changes

2022-11-22 09:29 UTC, rbrtbnfgl approved these changes

2022-11-22 18:06 UTC, merged