Update network_options.md with better IPv6 examples and a caution
rancher/rke2-docs pull request #113
Opened 2023-10-11 11:26 UTC by SitronNO

The documentation does not specify the size of IPv6 netmask, which may be a source of confusion and errors.
In addition, the documentation uses global unique addresses which are/will be assigned, which is bad practice. The preferred way is to use ULA (RFC 4193)

2023-10-11 23:16 UTC, brandond commented on docs/install/network_options.md
> +The cluster-cidr must have a netmask of /56, and the service-cidr must be /108 or smaller.
I don't believe this is accurate. Other sizes are possible, but alternate selections should be combined with changes to the IPv6 CIDR masks.

2023-10-11 23:17 UTC, brandond commented
cc @manuelbuil 

If we change here, we should change k3s docs as well.

2023-10-12 05:55 UTC, SitronNO commented on docs/install/network_options.md
> +The cluster-cidr must have a netmask of /56, and the service-cidr must be /108 or smaller.
I tried a netmask of /64 for the cluster-cidr, and the result was that Cilium reported `level=warning msg="Waiting for k8s node information" error="required IPv4 PodCIDR not available" subsys=k8s`. This error-message disappered when I increased the netmask of /56.
I also tried a netmask of /64 for service-cidr, but then I found an error-message in a log stating that the netmask must be >= /108.

Now, I have realized I have only tried this with Cilium as CNI, and I do not know if the other CNI has other requirements.

2023-10-12 08:45 UTC, rbrtbnfgl commented on docs/install/network_options.md
> +The cluster-cidr must have a netmask of /56, and the service-cidr must be /108 or smaller.
you need to change the node cluster CIDR mask len `kube-controller-manager-arg: "--node-cidr-mask-size-ipv6=xx"` at least for IPv6 pod CIDR; there should be another flag for the service-cidr. For the Cilium log are you sure you didn't change other flag for IPv4 it seems unrelated to the IPv6 size.

2023-10-13 12:34 UTC, SitronNO commented
I have now run several tests with all three CNI's and with different netmasks. See all test-results below, but my findings:
- The "service-cidr" mask must be >= /108. If not, the kube-apiserver will not start and throw an error-messages. Type of CNI does not matter.
- When using Cilium or Canal as CNI, the mask for "cluster-cidr" must be > /64. If not, all other nodes than the first master will not be able to run pods.
- When using Calico, the mask for "cluster-cidr" can be /64. All pods will get assigned a random IPv6 in the specified network.

**Test setup**
Master-node: Ubuntu 20.04 LTS as a VM. Servername: "server30". RKE2 version: v1.26.9-rke2r1
Agent-node: Ubuntu 20.04 LTS as a VM. Servername: "server31". RKE2 version: v1.26.9-rke2r1

**Test 1**
CNI: Cilium
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/64`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/64`

_Result_
rke2 server will not start.
Log (kube-apiserver): `"command failed" err="specified --service-cluster-ip-range[1] is too large; for 128-bit addresses, the mask must be >= 108"`

**Test 2**
CNI: Default (Canal)
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/64`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/64`

_Result_
rke2 server will not start.
Log (kube-apiserver): `"command failed" err="specified --service-cluster-ip-range[1] is too large; for 128-bit addresses, the mask must be >= 108"`

**Test 3**
CNI: Calico
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/64`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/64`

_Result_
rke2 server will not start.
Log (kube-apiserver): `"command failed" err="specified --service-cluster-ip-range[1] is too large; for 128-bit addresses, the mask must be >= 108"`

**Test 4**
CNI: Cilium
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/64`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/112`

_Result_
rke2-server will start.
rke2-agent starts, but no new pods are assigned to the node.
rke2-agent are not able to start cilium pod.
Running `get node server30 -o jsonpath='{.spec.podCIDRs}'` returns:
`["10.42.0.0/24","fd3a:5199:fd53:200::/64"]`
Running `get node server31 -o jsonpath='{.spec.podCIDRs}'` returns nothing.
Log on server31 (cilium-clkks_kube-system_cilium-agent): `level=warning msg="Waiting for k8s node information" error="required IPv4 PodCIDR not available" subsys=k8s`

**Test 5**
CNI: Default (Canal)
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/64`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/112`

_Result_
rke2-server will start.
rke2-agent starts, new pods are assigned to the node, but all failes with "ContainerCreating":
`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8d2088636add9c1cd9b00cf5c64e3c200c34e85e50af065877df87fa8e5f5e23": plugin type="calico" failed (add): no podCidr for node server31`
rke2-agent are not able to start canal pod.
Running `get node server30 -o jsonpath='{.spec.podCIDRs}'` returns:
`["10.42.0.0/24","fd3a:5199:fd53:200::/64"]`
Running `get node server31 -o jsonpath='{.spec.podCIDRs}'` returns nothing.
Log on server31 (rke2-canal-h4jtv_kube-system_install-cni): `Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.`

**Test 6**
CNI: Default (Calico)
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/64`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/112`

_Result_
rke2-server will start.
rke2-agent starts, new pods are assigned to the node
Running `get node server30 -o jsonpath='{.spec.podCIDRs}'` returns:
`["10.42.0.0/24","fd3a:5199:fd53:200::/64"]`
Running `get node server31 -o jsonpath='{.spec.podCIDRs}'` returns nothing.
Pods on server30 gets IP's like:
`10.42.63.202/32,fd3a:5199:fd53:200:4025:4b91:6c60:3fca/128`
`10.42.63.203/32,fd3a:5199:fd53:200:4025:4b91:6c60:3fcb/128`
Pods on server30 gets IP's like:
`10.42.75.9/32,fd3a:5199:fd53:200:db1a:e8df:27f1:a709/128`
`10.42.75.8/32,fd3a:5199:fd53:200:db1a:e8df:27f1:a708/128`
`10.42.75.10/32,fd3a:5199:fd53:200:db1a:e8df:27f1:a70a/128`

**Test 7**
CNI: Cilium
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/62`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/112`

_Result_
rke2-server will start.
rke2-agent starts, new pods are assigned to the node
`.spec.podCIDRs` returns:
`server30	["10.42.0.0/24","fd3a:5199:fd53:200::/64"]`
`server31	["10.42.1.0/24","fd3a:5199:fd53:201::/64"]`

**Test 8**
CNI: Default (Canal)
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/62`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/112`

_Result_
rke2-server will start.
rke2-agent starts, new pods are assigned to the node
`.spec.podCIDRs` returns:
`server30	["10.42.0.0/24","fd3a:5199:fd53:200::/64"]`
`server31	["10.42.1.0/24","fd3a:5199:fd53:201::/64"]`


**Test 9**
CNI: Calico
cluster-cidr: `10.42.0.0/16,fd3a:5199:fd53:200::/62`
service-cidr: `10.43.0.0/16,fd3a:5199:fd53:300::/112`

_Result_
rke2-server will start.
rke2-agent starts, new pods are assigned to the node
`.spec.podCIDRs` returns:
`server30	["10.42.0.0/24","fd3a:5199:fd53:200::/64"]`
`server31	["10.42.1.0/24","fd3a:5199:fd53:201::/64"]`
Pods on server30 gets IP's like:
`10.42.63.208/32,fd3a:5199:fd53:203:9f4e:7249:6119:8dd0/128`
`10.42.63.208/32,fd3a:5199:fd53:203:9f4e:7249:6119:8dd0/128`
Pods on server31 gets IP's like:
`10.42.75.3/32,fd3a:5199:fd53:200:f037:5b71:fe8:4b03/128`
`10.42.75.2/32,fd3a:5199:fd53:200:f037:5b71:fe8:4b02/128`

2023-10-13 12:47 UTC, rbrtbnfgl commented
I think the errors that you got at least for IPv6 are expected. If you don't change `node-cidr-mask-size-ipv6` it will be using the default value of 64. In case the cluster CIDR is `/64` the first node will get the all the available IPs and then you'll get an error on the second node because there aren't enough IPs. This happen with Canal and Cilium that are using the Kube-controller as IPAM. Calico has a different IPAM that should be configured through helm Calico config.

2023-10-13 14:51 UTC, SitronNO commented
@rbrtbnfgl : Thanks for the clarifications. I have updated the docs in my PR.
But where do you specify `node-cidr-mask-size-ipv6` if you want to change it? According to the [documentation](https://docs.rke2.io/reference/server_config), this is not an option for rke2 server, and thus can not be specified in `/etc/rancher/rke2/config.yaml`?

2023-10-13 14:53 UTC, rbrtbnfgl commented
You can with `kube-controller-manager-arg: "--node-cidr-mask-size-ipv6=xx"`

2023-10-16 08:51 UTC, SitronNO commented
Thanks for the feedback. I have now updated the docs, and I believe it's good enough to be merged.

2023-10-16 19:37 UTC, dereknola requested changes
No need to modify the manifests, just add to the config file.

2023-10-16 19:37 UTC, dereknola commented on docs/install/network_options.md
> +When choosing a netmask for cluster-cidr, please note that `node-cidr-mask-size-ipv6` has a default value of /64 - thus this need to be changed if you choose a netmask of /64 or smaller for `cluster-
```suggestion
When choosing a netmask for cluster-cidr, please note that `node-cidr-mask-size-ipv6` has a default value of /64 - thus this need to be changed if you choose a netmask of /64 or smaller for `cluster-cidr`. This is accomplished by adding `kube-controller-manager-arg: "--node-cidr-mask-size-ipv6=xx"` to the RKE2 config.
```

2023-10-16 19:37 UTC, dereknola commented on docs/install/network_options.md
> +When choosing a netmask for cluster-cidr, please note that `node-cidr-mask-size-ipv6` has a default value of /64 - thus this need to be changed if you choose a netmask of /64 or smaller for `cluster-
```suggestion
When choosing a netmask for cluster-cidr, please note that `node-cidr-mask-size-ipv6` has a default value of /64 - thus this need to be changed if you choose a netmask of /64 or smaller for `cluster-cidr`. This is accomplished by adding `kube-controller-manager-arg: "--node-cidr-mask-size-ipv6=xx"` to the RKE2 config.
```

2024-03-08 17:43 UTC, closed without merging