Update `Nginx Ingress` entry to be more accurately `Ingress-Nginx`
rancher/rke2-docs pull request #117
Opened 2023-10-31 01:49 UTC by joshpaulchan

## What

- [x] updates the `Nginx Ingress Controller` entry to be `Ingress-Nginx`

## Why

I figured this was more accurate given the current copy on the surface refers to a different ingress controller, and an easy thing to fix!

2023-10-31 05:19 UTC, brandond commented
This was consistent with upstream at the time we added it, but does appear that the upstream project has made an attempt to rebrand or at least be more consistent about branding. Note the changes in https://github.com/kubernetes/ingress-nginx/commit/1614027cd42aa3fac53d62afc235b86adec7543d

2023-10-31 13:47 UTC, joshpaulchan commented
@brandond Sweet! Glad it's further differentiating itself from the proprietary nginx ingress controller. Per this PR, let me know if I should tweak it in any way!

2023-10-31 16:42 UTC, brandond requested changes

2023-10-31 16:42 UTC, brandond commented on docs/architecture.md
> +- [Ingress-Nginx Controller][io-ingress-nginx]
It looks like upstream is not hyphenating
```suggestion
- [Ingress Nginx Controller][io-ingress-nginx]
```

2023-10-31 16:43 UTC, brandond commented on docs/architecture.md
> +- [Ingress-Nginx Controller][io-ingress-nginx]
thanks for suggesting this change!

2023-10-31 16:44 UTC, brandond commented
thanks for pointing this out!

2023-10-31 17:27 UTC, brandond approved these changes

2023-11-01 16:43 UTC, dereknola approved these changes

2023-11-01 17:24 UTC, manuelbuil approved these changes

2023-11-01 17:28 UTC, merged