updated docs to reflect support amazon linux 2023
rancher/rke2-docs pull request #118
Opened 2023-10-31 04:13 UTC by zackbradys

Updated `rke2-docs` to reflect support for Amazon Linux 2023 in RKE2 PR -> https://github.com/rancher/rke2/pull/4973

* Related RKE2 Issue: https://github.com/rancher/rke2/issues/4527
* Related AL2023 Issue: https://github.com/amazonlinux/amazon-linux-2023/issues/409

2023-10-31 05:24 UTC, brandond requested changes
Support for new Linux distributions needs to be approved by our product management and QA teams.

cc @caroline-suse-rancher @rancher-max

2023-11-17 21:54 UTC, zackbradys commented
Has there been any updates on this? Any additional information needed from me?

@brandond @caroline-suse-rancher @rancher-max

2023-11-27 15:36 UTC, caroline-suse-rancher commented
> Support for new Linux distributions needs to be approved by our product management and QA teams.
> 
> cc @caroline-suse-rancher @rancher-max

@brandond We discussed with product, and decided that this can be included! Please merge when ready :)

2023-11-27 18:35 UTC, brandond approved these changes

2023-11-27 18:42 UTC, merged