Update configuration.md
rancher/rke2-docs pull request #144
Opened 2024-01-06 16:26 UTC by suryatejaboorlu

2024-01-18 18:04 UTC, dereknola commented
You should create your config before you install or before you start the RKE2 service.

2024-01-18 18:43 UTC, brandond requested changes

2024-01-18 18:43 UTC, brandond commented on docs/install/configuration.md
> +The RKE2 config file needs to be created manually. You can do that by running `touch /etc/rancher/rke2/config.yaml` as a privileged user. Also, RKE2 systemd service needs to be restarted after adding
```suggestion
The RKE2 config file needs to be created manually. You can do that by running `touch /etc/rancher/rke2/config.yaml` as a privileged user. If the configuration is changed after starting RKE2, the service must be restarted to apply the new configuration.
```

2024-01-19 07:49 UTC, suryatejaboorlu commented
Thanks @brandond. In our case we need to inject some kubectl arguments which we had to bring in in the middle of project. In this case we will definitely restart the RKE2 server for the config to get applied.

2024-01-19 07:51 UTC, suryatejaboorlu commented
> You should create your config before you install or before you start the RKE2 service.
Thank you @dereknola. Most of the users don't know that we need to restart the rke2 service if the config file is created after sometime of deployment. In our case --pod-infra-container-image where the GC is deleting a pause image.

2024-01-23 20:52 UTC, dereknola approved these changes

2024-01-25 23:07 UTC, brandond approved these changes

2024-01-26 18:23 UTC, merged