Add information on the generic `cis` profile
rancher/rke2-docs pull request #156
Opened 2024-01-22 20:13 UTC by dereknola

Addresses: https://github.com/rancher/rke2-docs/issues/110

2024-01-22 20:22 UTC, brandond commented on docs/security/hardening_guide.md
> +Additionally, it ensures that upgrades to RKE2 do not require a change to existing configuration. Whatever changes are necessary to pass the newer associated CIS benchmark with automatically be appli
```suggestion
Use of the generic `cis` profile ensures that upgrades to RKE2 do not require a change to existing configuration. Whatever changes are necessary to pass applicable CIS benchmark will be automatically applied.
```

2024-01-22 20:23 UTC, brandond commented on docs/security/hardening_guide.md
> +The CIS Benchmark requires that the etcd data directory be owned by the `etcd` user and group. This implicitly requires the etcd process run as the host-level `etcd` user. To achieve this, RKE2 takes
Should we list `cis` first, since it's preferred?
```suggestion
The CIS Benchmark requires that the etcd data directory be owned by the `etcd` user and group. This implicitly requires the etcd process run as the host-level `etcd` user. To achieve this, RKE2 takes several steps when started with a valid `cis` or `cis-1.XX` profile:
```

2024-01-22 20:24 UTC, dereknola commented on docs/security/hardening_guide.md
> +The CIS Benchmark requires that the etcd data directory be owned by the `etcd` user and group. This implicitly requires the etcd process run as the host-level `etcd` user. To achieve this, RKE2 takes
Yeah that makes sense

2024-01-22 21:03 UTC, brandond approved these changes

2024-01-24 17:26 UTC, vitorsavian requested changes

2024-01-24 19:24 UTC, vitorsavian approved these changes

2024-01-26 18:29 UTC, merged