Added config to enable hubble in cilium
rancher/rke2-docs pull request #168
Opened 2024-02-23 14:37 UTC by rbrtbnfgl

Added config file on Cilium tab with the values needed to enable Hubble.

2024-02-23 14:40 UTC, manuelbuil requested changes

2024-02-23 14:40 UTC, manuelbuil commented on docs/install/network_options.md
> +Cilium included also an osservability platform called [Hubble](https://docs.cilium.io/en/stable/overview/intro/#what-is-hubble)
`includes`

2024-02-23 17:21 UTC, dereknola approved these changes

2024-02-23 17:24 UTC, brandond approved these changes

2024-02-23 17:25 UTC, brandond requested changes

2024-02-23 17:25 UTC, brandond commented on docs/install/network_options.md
> +Cilium includes also an osservability platform called [Hubble](https://docs.cilium.io/en/stable/overview/intro/#what-is-hubble)
```suggestion
Cilium includes also an observability platform called [Hubble](https://docs.cilium.io/en/stable/overview/intro/#what-is-hubble)
```

2024-02-27 00:02 UTC, brandond approved these changes

2024-02-28 18:53 UTC, merged