Point to the SUSE support matrix for RKE2
rancher/rke2-docs pull request #183
Opened 2024-03-29 19:19 UTC by dereknola

Addresses: https://github.com/rancher/rke2-docs/issues/174
Signed-off-by: Derek Nola <derek.nola@suse.com>

2024-03-29 19:40 UTC, brandond approved these changes

2024-04-01 05:41 UTC, manuelbuil requested changes

2024-04-01 05:41 UTC, manuelbuil commented on docs/install/requirements.md
> +See the (RKE2 Support Matrix)[https://www.suse.com/suse-rke2/support-matrix/all-supported-versions/rke2-v1-29/] for all the OS versions that have been validated with RKE2. In general, RKE2 should wor
`https://www.suse.com/suse-rke2/support-matrix/all-supported-versions` works for me too and it seems like it points to the latest version. That's probably better as we would not need to keep updating the URL

2024-04-01 17:01 UTC, dereknola commented on docs/install/requirements.md
> +See the (RKE2 Support Matrix)[https://www.suse.com/suse-rke2/support-matrix/all-supported-versions/rke2-v1-29/] for all the OS versions that have been validated with RKE2. In general, RKE2 should wor
Thanks I was trying to find a link for "latest"!

2024-04-01 17:21 UTC, manuelbuil approved these changes

2024-04-01 22:18 UTC, merged