Organize networking docs differently
rancher/rke2-docs pull request #193
Opened 2024-04-16 15:59 UTC by manuelbuil

Following on from what was done in K3s, this PR does a similar work for RKE2. It combines all Networking options into one directory where it contains three different documents:
* basic-network-options
* multus-sriov
* networking services

2024-04-16 16:25 UTC, dereknola requested changes
Now that you have a whole page on multus-sriov, are you going to remove the section https://docs.rke2.io/install/network_options#using-multus-with-sr-iov?

2024-04-16 16:25 UTC, dereknola commented on docs/networking/networking.md
> +---
Remove this file, RKE2 docs don't have top level directory files, unlike K3s.

2024-04-16 16:29 UTC, manuelbuil commented on docs/networking/networking.md
> +---
ah, thanks!

2024-04-16 16:29 UTC, manuelbuil commented
> Now that you have a whole page on multus-sriov, are you going to remove the section https://docs.rke2.io/install/network_options#using-multus-with-sr-iov?

Yes, I think that is done

2024-04-16 17:02 UTC, dereknola approved these changes

2024-04-17 01:17 UTC, mgfritch approved these changes

2024-04-17 05:38 UTC, merged