Add "How to modify folder to hold state"
rancher/rke2-docs pull request #209
Opened 2024-05-16 01:02 UTC by masap

SURE-7512.

2024-05-16 01:07 UTC, brandond requested changes

2024-05-16 01:07 UTC, brandond commented on docs/advanced.md
> +We are planning to allow the default path to be modified using the `data-dir` option.
This is not an accurate statement. RKE2 already supports changing this path via data-dir; it is Ranchers provisioning framework that does not allow for changing the data-dir setting. I think this docs change would be better suited for the Rancher docs, not the rke2 docs.

2024-05-16 01:49 UTC, masap commented on docs/advanced.md
> +We are planning to allow the default path to be modified using the `data-dir` option.
Thank you for comment.  I removed notes about `data-dir`.

2024-05-16 17:56 UTC, brandond commented on docs/advanced.md
> +## How to create symbolic link to RKE2 related directory
I'm still unclear on what you mean by `RKE2 related directory` We don't use the term "RKE2 related directory" anywhere else in our documentation, and it sounds like you're describing how to relocate the RKE2 data-dir using a symlink instead of changing the flag value. Can we perhaps refer to it that way?

2024-05-17 00:38 UTC, masap commented on docs/advanced.md
> +## How to create symbolic link to RKE2 related directory
I understood this article should not be in RKE2 document. I will drop this.

2024-05-17 00:38 UTC, closed without merging