Update uninstall.md to point to Rancher docs for Rancher deployed RKE…
rancher/rke2-docs pull request #234
Opened 2024-07-12 01:29 UTC by Tejeev

…2 clusters

The process differs so figured it's worth being specific and pointing users where they want to go.  Not sure if I used the callout correctly ':)

2024-07-15 18:14 UTC, dereknola requested changes
Thanks for the PR.

2024-07-15 18:14 UTC, dereknola commented on docs/install/uninstall.md
> +For instructions for cleaning a _Rancher deployed RKE2 cluster_ see: [https://docs.rke2.io/install/uninstall](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/cle
```suggestion
For cleaning a Rancher deployed RKE2 cluster see: [Clean Cluster Nodes](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes#cleaning-up-nodes)
```

2024-08-08 21:24 UTC, dereknola approved these changes

2024-08-08 21:47 UTC, VestigeJ approved these changes

2024-08-09 00:01 UTC, galal-hussein approved these changes

2024-08-09 14:31 UTC, merged