Add kine and runtimes search docs
rancher/rke2-docs pull request #281
Opened 2024-11-07 18:44 UTC by vitorsavian

Decided to change how rke2 docs are for backup and restore and add kine docs too

the behavior for kine in rke2 is the same as for k3s, so it only need a little bit of changes

2024-11-11 18:34 UTC, dereknola commented on docs/datastore/overview.md
> +| `--datastore-keyfile` | `RKE2_DATASTORE_KEYFILE` | TLS key file used for client certificate based authentication to your datastore. See the previous `datastore-certfile` parameter for more details.
We don't refer to RKE2 options as CLI flags, as 99.9% of the time the user is always directed to use the configuration file.

```suggestion
| Options | Environment Variable | Description
|------------|-------------|------------------
| `datastore-endpoint` | `RKE2_DATASTORE_ENDPOINT` | Specify a PostgreSQL, MySQL, or etcd connection string. This is a string used to describe the connection to the datastore. The structure of this string is specific to each backend and is detailed below. |
| `datastore-cafile` | `RKE2_DATASTORE_CAFILE` | TLS Certificate Authority (CA) file used to help secure communication with the datastore. If your datastore serves requests over TLS using a certificate signed by a custom certificate authority, you can specify that CA using this parameter so that the Rke2 client can properly verify the certificate. |
| `datastore-certfile` | `RKE2_DATASTORE_CERTFILE` | TLS certificate file used for client certificate based authentication to your datastore. To use this feature, your datastore must be configured to support client certificate based authentication. If you specify this parameter, you must also specify the `datastore-keyfile` parameter. |
| `datastore-keyfile` | `RKE2_DATASTORE_KEYFILE` | TLS key file used for client certificate based authentication to your datastore. See the previous `datastore-certfile` parameter for more details. |

```

2024-11-11 18:34 UTC, dereknola commented on docs/datastore/overview.md
> +  If you only supply `postgres://`  as the endpoint, Rke2 will attempt to do the following:
Nit extra space
```suggestion
  If you only supply `postgres://` as the endpoint, Rke2 will attempt to do the following:
```

2024-11-11 18:38 UTC, dereknola commented on docs/datastore/overview.md
> +---
The RKE2 website in general does not contain "Overview" pages, which is a different design than the K3s website. Everythibng past the inital `Rke2 datastore options:`  section should be moved to a different page, most likely the new `external.md` page

2024-11-11 18:38 UTC, dereknola commented on docs/datastore/overview.md
> +If you wish to use an external datastore such as PostgreSQL, MySQL, or etcd you must set the `datastore-endpoint` parameter so that Rke2 knows how to connect to it. You may also specify parameters to
Continuing from the comment above, move all these sections into the external.md page

2024-11-11 18:39 UTC, dereknola commented on docs/datastore/ha.md
>  You should see your server nodes in the Ready state.
I don't think we should move this section just to match the K3s website. IMO this page is better where it is, in the installation group.

2024-11-11 18:42 UTC, dereknola commented on docs/datastore/backup_restore.md
> +## Experimental
```suggestion
## External DB Backups (Experimental)
```
This title is too vague.

2024-11-11 18:45 UTC, dereknola commented on docs/datastore/overview.md
> +Rke2 have a set of datastores that can be use, but only oficially support Embedded etcd, the other datastores are experimental.
```suggestion
RKE2 officially supports Embedded etcd, other external datastores are experimental.
```

2024-11-11 18:46 UTC, dereknola commented on docs/datastore/overview.md
> +Rke2 datastore options:
```suggestion
RKE2 datastore options:
```

Check the whole PR, but every mention of RKE2 needs to be capitalized. We never refer to it a `Rke2`

2024-11-11 19:25 UTC, vitorsavian commented on docs/datastore/ha.md
>  You should see your server nodes in the Ready state.
I thought it could be better to have everything related to the datastore inside a specific section, but I can see why it's better to maintain in the install, since it's the first section that a user will see and kine is still experimental.

2024-11-11 20:04 UTC, dereknola requested changes

2024-11-11 20:04 UTC, dereknola commented on docs/datastore/external.md
> +If you wish to use an external datastore such as PostgreSQL, MySQL, or etcd you must set the `datastore-endpoint` parameter so that RKE2 knows how to connect to it. You may also specify parameters to
Nit, but we don't talk about CLI.

2024-11-11 20:04 UTC, dereknola commented on docs/datastore/external.md
> +You will first need to create an external datastore for the cluster. See the [Datastore overview](overview.md) documentation for more details.
Broken link now that overview.md doesn't exist

2024-11-11 20:04 UTC, dereknola commented on docs/datastore/external.md
> +:::
I would just copy the HA instructions note in this section
```suggestion
:::note 
The RKE2 config file needs to be created manually. You can do that by running touch /etc/rancher/rke2/config.yaml as a privileged user. 
:::
```

2024-11-20 18:26 UTC, dereknola approved these changes

2024-11-20 18:27 UTC, merged