Add information about embedded registry
rancher/rke2-docs pull request #296
Opened 2024-12-18 11:06 UTC by manuelbuil

This PR:
* Adds information about the embedded registry (mostly copied from k3s)
* Includes extra information about private registries (thanks @dereknola )

2024-12-18 18:38 UTC, dereknola requested changes

2024-12-18 18:38 UTC, dereknola commented on docs/install/airgap.md
> +K3s includes an embedded distributed OCI-compliant registry mirror.
```suggestion
RKE2 includes an embedded distributed OCI-compliant registry mirror.
```

2024-12-18 18:38 UTC, dereknola commented on docs/install/airgap.md
> +RKE2 can be installed in an air-gapped environment with three different methods. You can either deploy via the [rke2-airgap-images tarball release artifact](#tarball-method), by using a [private regi
We can't install RKE2 via the embedded registry. It just makes the image pulls easier.

2024-12-18 18:38 UTC, dereknola commented on docs/install/registry_mirror.md
> +The Embedded Registry Mirror is available as an experimental feature as of January 2024 releases: v1.26.13+rke2r1, v1.27.10+rke2r1, v1.28.6+rke2r1, v1.29.1+rke2r1
We are going straight to GA with this feature. 
```suggestion
The Embedded Registry Mirror is available as of December 2024 releases: <INSERT VERSIONS>
```

2024-12-18 18:38 UTC, dereknola commented on docs/install/registry_mirror.md
> +When enabled at a cluster level, all nodes will host a local OCI registry on port 6443,
Double checking that this is true for RKE2, on port 6443?

2024-12-18 20:50 UTC, brandond commented on docs/install/airgap.md
> +RKE2 can be installed in an air-gapped environment with three different methods. You can either deploy via the [rke2-airgap-images tarball release artifact](#tarball-method), by using a [private regi
I think the reference here is to an existing private registry, not to the embedded registry.

2024-12-18 20:51 UTC, brandond commented on docs/install/registry_mirror.md
> +The Embedded Registry Mirror is available as an experimental feature as of January 2024 releases: v1.26.13+rke2r1, v1.27.10+rke2r1, v1.28.6+rke2r1, v1.29.1+rke2r1
Maybe available as of X, GA as of Y?

2024-12-18 20:52 UTC, brandond commented on docs/install/registry_mirror.md
> +When enabled at a cluster level, all nodes will host a local OCI registry on port 6443,
It's on the supervisor port. So 9345 for rke2.

2024-12-19 08:45 UTC, manuelbuil commented on docs/install/airgap.md
> +K3s includes an embedded distributed OCI-compliant registry mirror.
Great catch Derek, thanks!

2024-12-19 08:47 UTC, manuelbuil commented on docs/install/airgap.md
> +RKE2 can be installed in an air-gapped environment with three different methods. You can either deploy via the [rke2-airgap-images tarball release artifact](#tarball-method), by using a [private regi
That's what I wanted to reflect here because that's what we are suggesting to a customer. I'll add a bit more explanation to it, right now it's impossible to know for sure that we mean that

2024-12-19 08:53 UTC, manuelbuil commented on docs/install/registry_mirror.md
> +The Embedded Registry Mirror is available as an experimental feature as of January 2024 releases: v1.26.13+rke2r1, v1.27.10+rke2r1, v1.28.6+rke2r1, v1.29.1+rke2r1
Done

2024-12-19 08:54 UTC, manuelbuil commented on docs/install/registry_mirror.md
> +When enabled at a cluster level, all nodes will host a local OCI registry on port 6443,
Thanks

2024-12-19 18:53 UTC, dereknola approved these changes

2024-12-19 19:25 UTC, brandond requested changes
one more nit on the private registry stuff ;)

2024-12-19 19:25 UTC, brandond commented on docs/install/airgap.md
> +RKE2 can be installed in an air-gapped environment with two different methods. You can either deploy via the [rke2-airgap-images tarball release artifact](#tarball-method) or by using a [private regi
I wouldn't say that you can "install" using the embedded registry, as you still need to get the artifact tarball from somewhere - it does not solve the install problem, just the image pull problem.

I would say that you can use the embedded registry in an airgapped environment.

```suggestion
RKE2 can be installed in an air-gapped environment with two different methods. You can either deploy images via the [rke2-airgap-images tarball release artifact](#tarball-method) or by using a [private registry](#private-registry-method). It is also possible to use the [embedded registry mirror](#embedded-registry-mirror) as long as there is at least one cluster member that has access to the required images.
```

2024-12-19 21:21 UTC, manuelbuil commented on docs/install/airgap.md
> +RKE2 can be installed in an air-gapped environment with two different methods. You can either deploy via the [rke2-airgap-images tarball release artifact](#tarball-method) or by using a [private regi
it's a good suggestion

2024-12-19 21:29 UTC, manuelbuil commented
Let me remove the exerimental/GA message from the airgap.md and leave it in the embeded-registry.md. It should be enough to have it in one place

2024-12-20 18:02 UTC, dereknola approved these changes

2024-12-21 21:54 UTC, merged