Add info about airgap + upgrades
rancher/rke2-docs pull request #297
Opened 2024-12-18 11:47 UTC by manuelbuil

Add information in RKE2 about how to upgrade clusters using airgap. The information is basically copied from K3s and slightly changed

2024-12-18 18:39 UTC, dereknola approved these changes

2024-12-18 20:53 UTC, brandond approved these changes

2024-12-19 19:19 UTC, brandond requested changes

2024-12-19 19:19 UTC, brandond commented on docs/upgrades/manual_upgrade.md
> +4. Launch the new rke2 process
```suggestion
3. Restart the rke2-server or rke2-agent service
```

I frequently run into new users who are confused by the docs and just end up running `rke2 server ...` in their terminal and can't figure out how to keep it running when they log out.

2024-12-20 11:15 UTC, merged