Expand on the datastore explanation
rancher/rke2-docs pull request #298
Opened 2024-12-19 08:42 UTC by manuelbuil

This PR expands our information on datastores:
* Separates docs for embedded datastores and external datastores
* Adds a small introduction

2024-12-19 18:00 UTC, dereknola requested changes

2024-12-19 18:00 UTC, dereknola commented on docs/datastore/embedded.md
> +
```suggestion
* **Embedded [Etcd](https://etcd.io/)**  
  Embedded Etcd is the default datastore, and will be used if no other datastore configuration is present.
* **Embedded [SQLite](https://www.sqlite.org/index.html)**  
  SQLite cannot be used on clusters with multiple servers. It uses project [kine](https://github.com/k3s-io/kine)

## Embedded Etcd
The default option. Launch RKE2 with no additional configuration
```

This seems redundant, but its weird that we mention both above, and then never talk about it again.

Maybe just rework this section, removing the overview options and just 

## Datastore options
## Embedded etcd
## SQLite 
- note that its single server

2024-12-19 21:54 UTC, manuelbuil commented on docs/datastore/embedded.md
> +
Have a look now. I think it looks better

2024-12-19 22:05 UTC, brandond approved these changes

2024-12-20 18:03 UTC, dereknola approved these changes

2024-12-21 21:53 UTC, merged