Update linux_uninstall.md
rancher/rke2-docs pull request #33
Opened 2022-12-19 15:45 UTC by dmathern86

rke2-uninstall.sh script is under SLES in another location.

2022-12-20 19:14 UTC, brandond approved these changes

2022-12-20 19:28 UTC, nikolaishields approved these changes

2022-12-20 19:48 UTC, dereknola requested changes
This is depending on your installation process determined via INSTALL_RKE2_TAR_PREFIX
```
#     Default is /usr/local, unless /usr/local is read-only or has a dedicated mount point,
#     in which case /opt/rke2 is used instead.
```
Testing on opensuse leap 15.4 ( I don't have easy access to SLES) I am seeing `/usr/local/bin/rke2-uninstall.sh`... is `/usr/local` read-only by default on SLES?

2022-12-20 20:36 UTC, brandond commented
Yeah, I didn't want to nit it too much, but it will go into /opt/rke2 on any host using btrfs subvolumes for different mount points. I know this includes opensuse and sle micro; for cloud images it may depend on how the filesystem is laid out?

2022-12-23 14:06 UTC, dmathern86 reviewed
looks good.

2023-01-03 17:53 UTC, closed without merging