Remove experimental flag for SRIOV
rancher/rke2-docs pull request #68
Opened 2023-04-27 15:50 UTC by rancher-max

This has been re-validated and confirmed working as part of this April release cycle.

2023-04-27 17:47 UTC, brandond requested changes
nit

2023-04-27 17:47 UTC, brandond commented on docs/install/network_options.md
> +**This is no longer experimental as of April 2023 releases: v1.26.4+rke2r1, v1.25.9+rke2r1, and v1.24.13+rke2r1**
```suggestion
**SR-IOV support was added in v1.21.2+rke2r1, and is fully supported starting with the April 2023 releases: v1.26.4+rke2r1, v1.25.9+rke2r1, and v1.24.13+rke2r1**
```

2023-04-27 17:52 UTC, rancher-max commented on docs/install/network_options.md
> +**This is no longer experimental as of April 2023 releases: v1.26.4+rke2r1, v1.25.9+rke2r1, and v1.24.13+rke2r1**
Updated with: "SR-IOV experimental support was added ... " plus the rest of your suggestion

2023-04-27 18:06 UTC, brandond approved these changes

2023-05-05 15:57 UTC, dereknola approved these changes

2023-05-05 15:57 UTC, merged