Change name of repository to match example
rancher/rke2-docs pull request #76
Opened 2023-06-13 08:17 UTC by tobiasgbg

2023-06-13 20:25 UTC, brandond requested changes

2023-06-13 20:25 UTC, brandond commented on docs/install/containerd_registry_configuration.md
> +For example, the following configuration would pull from the private registry at `https://registry.example.com:5000` for both `docker.io/busybox:latest` and `registry.example.com/library/busybox:late
You've replaced the implicit repository with the implicit registry, which seems like a questionable change. If you want to be technically correct, the full image would be:
```suggestion
For example, the following configuration would pull from the private registry at `https://registry.example.com:5000` for both `docker.io/library/busybox:latest` and `registry.example.com/library/busybox:latest`:
```

2023-07-20 18:15 UTC, dereknola commented
@tobiasgbg Is this still relevant?

2023-09-05 18:55 UTC, dereknola commented
Closing as no longer relevant

2023-09-05 18:55 UTC, closed without merging