Add docs for shipped CLI tools and log locations
rancher/rke2-docs pull request #78
Opened 2023-06-16 10:09 UTC by bashofmann

This adds documentation pages for

* List of shipped CLI tools (kubectl, ctr, crictl, etcdctl) and examples how to use them
* Locations of the various logs

Documenting this will help with debugging RKE2.

The information is taken from this excellent Gist https://gist.github.com/superseb/3b78f47989e0dbc1295486c186e944bf.

2023-06-16 10:15 UTC, bashofmann commented
This also fixes https://github.com/rancher/rke2/issues/639

2023-06-16 16:53 UTC, brandond requested changes

2023-06-16 16:53 UTC, brandond commented on docs/reference/cli_tools.md
> +## etcd
etcd is managed by rke2; we do not want to encourage people to interact with it directly. For example, they should not be running defrags on a running cluster member; this is done automatically during service startup.  Running a manual defrag will block all datastore IO and may cause apiserver outages if the operation takes more than a few seconds.

Even worse is telling them how to run `etcdctl check perf` - this will simulate a client workload by creating/updating/deleting keys and has been known to fill the datastore and cause sev1 outage incidents.

I think we should remove most if not all of this section. If anything we could perhaps leave a single entry on how to check endpoint status.

2023-06-16 16:58 UTC, dereknola requested changes

2023-06-16 16:58 UTC, dereknola commented on docs/reference/cli_tools.md
> +## etcd
Please remove this section on `etcdctl` we purposely do not give information on how to use etcdctl on the embedded etcd DB in rke2. Things such as `etcdctl check perf` and `etcdctl defrag` cause distribution to the etcd DB. We have had several customer problems (sev1 & 2) around them messing with the underlying DB.

2023-06-16 16:58 UTC, dereknola commented on docs/reference/cli_tools.md
> +/var/lib/rancher/rke2/bin/crictl --runtime-endpoint unix:///run/k3s/containerd/containerd.sock ps -a
You don't need to pass the endpoint if you export/set the config
```suggestion
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
/var/lib/rancher/rke2/bin/crictl ps
OR
/var/lib/rancher/rke2/bin/crictl --config /var/lib/rancher/rke2/agent/etc/crictl.yaml ps
```

2023-06-23 11:16 UTC, bashofmann commented on docs/reference/cli_tools.md
> +## etcd
Makes sense. I removed the etcd section.

2023-06-23 11:16 UTC, bashofmann commented on docs/reference/cli_tools.md
> +## etcd
Makes sense. I removed the etcd section.

2023-06-23 11:17 UTC, bashofmann commented on docs/reference/cli_tools.md
> +/var/lib/rancher/rke2/bin/crictl --runtime-endpoint unix:///run/k3s/containerd/containerd.sock ps -a
Thanks. I cleaned it up.

2023-06-23 18:51 UTC, dereknola approved these changes

2023-06-26 19:48 UTC, brandond requested changes

2023-06-26 19:48 UTC, brandond commented on docs/reference/logging.md
> +When running with systemd, the main RKE2 logs will be created in `/var/log/syslog` and viewed using `journalctl -u rke2-server` or `journalctl -u rke2-agent`.
```suggestion
When running with systemd, logs are sent to journald and can be viewed using `journalctl -u rke2-server` or `journalctl -u rke2-agent`. Some systemd configurations may also write combined logs to `/var/log/syslog`, in which case the rke2 logs will also be available there.
```

2023-06-26 19:48 UTC, brandond commented on docs/reference/logging.md
> +```
You might also mention that the logs can be accessed directly by tailing files in `/var/log/pods` - when things are not working right, this is often an easier way to get at things than by using crictl.

2023-06-26 19:48 UTC, brandond commented on docs/reference/logging.md
> +/var/lib/rancher/rke2/bin/crictl --runtime-endpoint unix:///run/k3s/containerd/containerd.sock logs <container_id>
I usually suggest exporting the endpoint, instead of passing it as a flag.
```suggestion
export CONTAINER_RUNTIME_ENDPOINT=unix:///run/k3s/containerd/containerd.sock
# list running containers
/var/lib/rancher/rke2/bin/crictl ps
# get logs from container by container id
/var/lib/rancher/rke2/bin/crictl logs <container_id>
```

2023-07-11 09:08 UTC, bashofmann commented on docs/reference/logging.md
> +```
I added this.

2023-07-13 19:53 UTC, brandond approved these changes

2023-07-13 23:17 UTC, merged