Clarify hostname prereq
rancher/rke2-docs pull request #79
Opened 2023-06-16 21:28 UTC by rancher-max

2023-06-16 21:59 UTC, brandond requested changes

2023-06-16 21:59 UTC, brandond commented on docs/install/requirements.md
> +If two or more of your machines have the same hostname, either change it or set the `node-name` parameter in the RKE2 config file for each node you add to the cluster to have a different node name.
We don't ever refer to RKE2 hosts as 'machines' in our docs; machines are a Rancher thing, so lets not use that terminology.  We also just added support for with-node-id to address this problem.

```suggestion
If two or more of your nodes have the same hostname, you must:
1. Change the hostnames so that they are unique.
2. Set the `node-name` parameter in the config file to a unique value.
3. Set the `with-node-id` parameter in the config file to `true`, to append a randomly generated ID number to the hostname.

:::info Version Gate

The `with-node-id` parameter is available starting with the 2023-05 releases (v1.27.2+rke2r1, v1.26.5+rke2r1, v1.25.10+rke2r1, v1.24.14+rke2r1)

:::

```

2023-07-13 23:21 UTC, brandond commented on docs/install/requirements.md
> +If two or more of your machines have the same hostname, either change it or set the `node-name` parameter in the RKE2 config file for each node you add to the cluster to have a different node name.
I guess I'm OK with it for now, but I may open a PR in the future to standardize on use of `node` (as the Kubernetes resource) and `host` (for the Linux host operating system that RKE2 is installed to). `machine` should be reserved for talking about the physical hardware or VM instance itself, and isn't something that RKE2 should be concerned with - I'd like to keep any references to that to just the Rancher docs.

2023-07-20 18:16 UTC, dereknola approved these changes

2023-07-24 19:56 UTC, brandond approved these changes

2023-07-25 15:31 UTC, merged