Added destination column on networking requirements
rancher/rke2-docs pull request #95
Opened 2023-09-01 10:49 UTC by rbrtbnfgl

Added destination column on network requirements (https://github.com/rancher/rke2/issues/4691)

2023-09-01 17:46 UTC, brandond requested changes
one nit on a port description; LGTM otherwise!

2023-09-01 17:46 UTC, brandond commented on docs/install/requirements.md
> +| TCP      | 9345        | RKE2 agent nodes  | RKE2 server nodes | Kubernetes API
Might as well fix this while we're here.
```suggestion
| TCP      | 9345        | RKE2 agent nodes  | RKE2 server nodes | RKE2 supervisor API
```

2023-09-06 16:39 UTC, brandond commented
@rbrtbnfgl you might also pull in the change from https://github.com/rancher/rke2-docs/pull/91

2023-09-06 16:41 UTC, dereknola approved these changes

2023-09-07 10:44 UTC, manuelbuil approved these changes

2023-09-07 16:47 UTC, rbrtbnfgl commented
Yes after @manuelbuil merges his PR I'll rebase and fix mine.

2023-09-07 18:52 UTC, brandond approved these changes
lgtm pending rebase

2023-09-08 12:05 UTC, merged